### ISSUE TITLE
Format in config file has priority over option in command line

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#30]
**Steps**
* I have config file with default
```
files:
    default:
        pull:
            format: "{{name .FileURI}}{{with .Locale}}_{{.}}{{end}}{{ext .FileURI}}"
```
* I ran pull files with another format. Something like this
```
cli files pull -l es --format="{{name .FileURI}}_ES{{ext .FileURI}}"
```

**Actual**
CLI downloaded with the format from config file. I had to comment it

**Expected**
Command line option should have priority over config file
