### ISSUE TITLE
feat: exclude some files from uploading

### ISSUE THREAD

**Issue by mdreizin** [Smartling/smartling-cli#44]
It would be nice to exclude files from uploading using `glob` patterns or just path to file:

```yaml
files:
    default:
        push:
            exclude:
            - lang/foo/*.json
    "translations/**/*.json":
        push:
            type: "json"
            # or use `exclude` here
            exclude:
            - lang/foo/*.json
```

If have `lang/foo/en-US.json` (or other files under `lang/foo/*`) then they will excluded from uploading:

1. `smartling.yml` is used:

```
smartling-cli files push
```

2. override via arguments:

```
smartling-cli files push --exclude=lang/foo/*.json
```

**`EXAMPLE`**:

https://github.com/Fitbit/smartling/blob/master/README.md (please see `Files.PathExclude` option)
https://github.com/Fitbit/smartling/blob/master/model/project_resource.go#L77
https://github.com/Fitbit/smartling/blob/master/model/project_resource_test.go#L39
